### ISSUE TITLE
Authentication not working (on premises, multi-context)

### ISSUE THREAD

**Issue by grahampugh** [jamf/jamf-laps-public#1]
Hi there, I'm excited to try out the app!

Unfortunately no authentication method is working for me. I've tried an API client, a local account with the correct permissions, and the admin account.

Useful context could be that I'm trying an on-prem instance which is multi-context, i.e. https://ourserver.com/mycontext. I mention this because sometimes Jamf trip over this type of URL. The instance is Jamf Pro 10.50.

Sure enough, if I use my sandbox cloud instance, the authorisation works.

**Comment by red5coder** [comment]
Hi Graham

Thanks for the feedback.

I don't have easy access to an on-prem instance.

Would it be possible to create an account for me on one of them, don't need any permissions, just enough to test the authentication piece. 

I can then check on what we need to change?

**Comment by red5coder** [comment]
Hi Graham,

Hold that thought, I can get one spun up. Let me test and get back to you.

**Comment by red5coder** [comment]
Hi Graham
I have identified the problem. 
Will test a fix shortly.

**Comment by grahampugh** [comment]
Awesome, thanks Richard!

Our instances are hidden inside our network, so I would not have been able to give you access. Thanks for finding another way!

**Comment by red5coder** [comment]
Will close this issue as this has been resolved in 1.0.1
