### ISSUE TITLE
Additional permission required for LAPS password read only Jamf Pro Account

### ISSUE THREAD

**Issue by erefneb** [jamf/jamf-laps-public#4]
In addition to the minimum permissions listed in the documentation the Jamf Pro account for LAPS password read only requires:
Jamf Pro Server Objects > Computers - Read
optionally – Jamf Pro Server Actions > View Disk Encryption Recovery Key

**Comment by red5coder** [comment]
Thank you for spotting this. Has been fixed. Have a nice day
