### ISSUE TITLE
Authentication works, but no serial number can be looked up

### ISSUE THREAD

**Issue by ArcOne** [jamf/jamf-laps-public#6]
I was able to set up Laps for testing in my JAMF Pro 11 test environment. When switching that to my 10.50.0-t1693149930 productions environment. I can fetch the  time settings but no matter what serial number I use all I get is cannot find the serial number error
![Screenshot 2023-10-24 at 16 27 33](https://github.com/jamf/jamf-laps-public/assets/26442500/0da99e93-78a3-4cd3-8429-5f212efc6dd0)
![Screenshot 2023-10-24 at 16 27 46](https://github.com/jamf/jamf-laps-public/assets/26442500/b340de11-0965-4699-82a4-7d379f28f4b5)
![Screenshot 2023-10-24 at 16 28 00](https://github.com/jamf/jamf-laps-public/assets/26442500/33c4cbf7-f448-48b5-be76-8f449241a911)
![Screenshot 2023-10-24 at 16 28 42](https://github.com/jamf/jamf-laps-public/assets/26442500/6c0e0b6b-8906-41b1-81fa-314cfad98503)

**Comment by red5coder** [comment]
Hi there

Can you very the permissions you have one the account.

Should have these?

**Comment by red5coder** [comment]
Read Computers, Update Local Admin Password Settings, View Local Admin Password Audit History, Send Local Admin Password Command, View Local Admin Password

**Comment by ArcOne** [comment]
Thre fix for me was the read computers permission. which I see is now a required permission for the app.
