### ISSUE TITLE
Response code for authentication: 401

### ISSUE THREAD

**Issue by nickandyson** [jamf/jamf-laps-public#8]
When I try to use the JAmf LAPS tool, even with a new account with full/admin permissions, I receive "Response code for authentication: 401" "No authentication token received"

<img width="1142" alt="image" src="https://github.com/jamf/jamf-laps-public/assets/70973289/86fd60ee-e1bd-4d5c-a860-abec02ade2fd">

**Comment by red5coder** [comment]
Hi Nick

At the moment I can't reproduce the issue.

One thing to check, if you are using a name/password combination , make sure the "Use API Roles and Clients" checkbox is unchecked.

Also have you tried using an API Role instead?

**Comment by red5coder** [comment]
Hi Nick

Was wondering if you had managed to try any of my suggestions.

As you are getting a 401 error, it suggests the app can reach the API end point but is failing the authentication.

**Comment by nickandyson** [comment]
Hi red5coder, when I run this on my personal Mac the issue is not present. This must be something with my corp network. Thank you for your time.
